### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by davebulaval** [yuedongP/BanditSum#4]
On the 
`logging.basicConfig(filename='%s.log' % log_name,
                        level=logging.INFO, format='%(asctime)s [INFO] %(message)s')`

I got this error 

`[...]/model.bag_of_words.avg_f.False.batch_avg.oracle_l.3.bsz.20.rl_loss.2.train_example_quota.-1.length_limit.-1.hidden.200.dropout.0.0.ext.log'`

Seems like it's missing some log file in the banditsum/log repository.

**Comment by YueDongCS** [comment]
Hi, can you show the error message? The logger is supposed to create the file and write a log into "model.bag_of_words.avg_f.False.batch_avg.oracle_l.3.bsz.20.rl_loss.2.train_example_quota.-1.length_limit.-1.hidden.200.dropout.0.0.ext.log". It is not required for testing or re-training.

**Comment by angeluau** [comment]
where pull request form David Beauchemin,i don't know

**Comment by YueDongCS** [comment]
So basically if you want to use our code in Python 3.7, you need to change import cPickle to pickle and add parenthesis for print functions.

**Comment by davebulaval** [comment]
I'll send the error message : 
`missingFile ... [...]/model.bag_of_words.avg_f.False.batch_avg.oracle_l.3.bsz.20.rl_loss.2.train_example_quota.-1.length_limit.-1.hidden.200.dropout.0.0.ext.log'`

1. Ok I will take a look to it.
2. @angeluau it's here : https://github.com/yuedongP/BanditSum/pull/3/
3. I'll take a look a pickle. Since almost all your print are () I really tought this was python 3.x

**Comment by YueDongCS** [comment]
Hi @davebulaval, I can't reproduce the same issue here. 
can you change the file_name in logging.basicConfig to "example.log" to see if the logger works properly?

**Comment by davebulaval** [comment]
Ok I got the error.
`
log_name = ".".join(("../log/model", [...]
`
You put `../` but the structure of the repository suggest that the level of the log should be in the root repository `./`.

With this modification it work.

**Comment by davebulaval** [comment]
Same error with the model summary saving 
actual code 
` parser.add_argument('--model_file', type=str, default='../model/summary.model') `
Suggestion to be coherent with the repository
`parser.add_argument('--model_file', type=str, default='./model/summary.model')`
